// <auto-generated />
using System;
using DogadjajiApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogadjajiApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617192620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogadjajiApp.Domains.Dogadjaj", b =>
                {
                    b.Property<int>("DogadjajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DogadjajId"));

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("LokacijaId")
                        .HasColumnType("int");

                    b.Property<string>("NazivDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Trajanje")
                        .HasColumnType("float");

                    b.Property<int>("VrstaDogadjajaVrstaId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaId")
                        .HasColumnType("int");

                    b.HasKey("DogadjajId");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("VrstaDogadjajaVrstaId");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.DogadjajPredavac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIVreme")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int>("PredavacId")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("PredavacId");

                    b.ToTable("DogadjajPredavaci");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Lokacija", b =>
                {
                    b.Property<int>("LokacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("NazivLokacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LokacijaId");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Predavac", b =>
                {
                    b.Property<int>("PredavacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredavacId"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oblast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PredavacId");

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Prijava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<string>("EmailUcesnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeUcesnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeUcesnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.VrstaDogadjaja", b =>
                {
                    b.Property<int>("VrstaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrstaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VrstaId");

                    b.ToTable("VrsteDogadjaja");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Dogadjaj", b =>
                {
                    b.HasOne("DogadjajiApp.Domains.Lokacija", "Lokacija")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogadjajiApp.Domains.VrstaDogadjaja", "VrstaDogadjaja")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("VrstaDogadjajaVrstaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("VrstaDogadjaja");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.DogadjajPredavac", b =>
                {
                    b.HasOne("DogadjajiApp.Domains.Dogadjaj", "Dogadjaj")
                        .WithMany("DogadjajPredavaci")
                        .HasForeignKey("DogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogadjajiApp.Domains.Predavac", "Predavac")
                        .WithMany("DogadjajPredavaci")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");

                    b.Navigation("Predavac");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Prijava", b =>
                {
                    b.HasOne("DogadjajiApp.Domains.Dogadjaj", "Dogadjaj")
                        .WithMany("Prijave")
                        .HasForeignKey("DogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Dogadjaj", b =>
                {
                    b.Navigation("DogadjajPredavaci");

                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Lokacija", b =>
                {
                    b.Navigation("Dogadjaji");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.Predavac", b =>
                {
                    b.Navigation("DogadjajPredavaci");
                });

            modelBuilder.Entity("DogadjajiApp.Domains.VrstaDogadjaja", b =>
                {
                    b.Navigation("Dogadjaji");
                });
#pragma warning restore 612, 618
        }
    }
}
