// <auto-generated />
using LocationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocationService.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    [Migration("20260630120000_AddBrojRezervacija")]
    partial class AddBrojRezervacija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationService.Domains.Lokacija", b =>
            {
                b.Property<int>("LokacijaId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaId"));

                b.Property<string>("Adresa")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("BrojRezervacija")
                    .HasColumnType("int");

                b.Property<int>("Kapacitet")
                    .HasColumnType("int");

                b.Property<string>("NazivLokacije")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("LokacijaId");

                b.ToTable("Lokacije");
            });
#pragma warning restore 612, 618
        }
    }
}